<!-- BEGIN -->
<html lang="en">
         <head>
             <meta charset="utf-8" />
             <meta name="viewport" content="width=device-width, initial-scale=1" />
             <title>Main page</title>
                     <title>/users</title>
                     <title>/</title>
         </head>
    <title>Hello everyone!</title>
</head>
<body>
<div class="mx-auto p-4 py-md-5">
    <main>
        <a href="/users">Users</a>
    </main>
</div>
</body>
</html>
<!-- END -->
