<!-- BEGIN -->
@import gg.jte.Content
@param Content content

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Main page</title>
                <title>/users</title>
                <title>/</title>
    </head>
    <body>
        <footer>
            <p>© DaryaSHCH </p>
          </footer>
        ${content}
    </body>
</html>
<!-- END -->
